### ISSUE TITLE
v2.0.7 pino-dev: command not found

### ISSUE THREAD

**Issue by TongChia** [dnjstrom/pino-dev#32]
installed by yarn v1.22.15
```json
  "scripts": {
    "dev": "ts-node-dev --no-notify --respawn --transpile-only src/index.ts -vvv | npx pino-dev"
  },
```
```shell
sh: pino-dev: command not found
```

i can install it with v2.0.6, but got date-fns error:
```shell
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule
```

**Comment by dnjstrom** [comment]
Hi @TongChia! Thanks for reporting these issues! 🙌 

For the first issue, I recently changed the way new packages are published and it seems the build wasn't actually included in the package contents for version v2.0.7.

About the second issue, it looks like you might be using a preformatted string for the `time` property rather than a `number` timestamp? I've updated `pino-dev` to pass such strings through unchanged rather than attempting to reformat them.

Both issues should be resolved in the latest patch release: `v2.0.11`. Please reach out if you have any further issues!
